stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: "repo-pub-docker.sourdin.ovh"

services:
  - docker:dind

build:
  image: proxy-docker.sourdin.ovh/docker
  stage: build
  when: always
  script:
    - docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build -t $REGISTRY/devops/s3toolkit:$CI_COMMIT_TAG .
    - docker push $REGISTRY/devops/s3toolkit:$CI_COMMIT_TAG
    - docker logout $REGISTRY
  rules:
    - if: $CI_COMMIT_TAG
